# Generated by Django 5.2.8 on 2025-11-26 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pittrain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitairporttrainfact',
            name='rank',
            field=models.IntegerField(default=5, help_text='Rank from 1 (bad) to 10 (awesome)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
